# Generated by Django 4.2.15 on 2024-11-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Free Trial', 'Free Trial')], default='Free Trial', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('7 AM', '7 AM'), ('8 AM', '8 AM'), ('9 AM', '9 AM'), ('1 PM', '1 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('6 PM', '6 PM'), ('7:30 PM', '7:30 PM')], default='7 AM', max_length=10),
        ),
    ]
